/**
 * vite-env.d.ts — pulls in Vite's TypeScript type definitions so
 * `import.meta.env`, `?url` asset imports, and other Vite-specific features
 * type-check correctly. Auto-generated by `npm create vite` — do not edit.
 */
/// <reference types="vite/client" />
